doctrine:
    dbal:
        default_connection: sqlsrv
        connections:
            sqlsrv:
                host: '%env(DATABASE_HOST_SQLSRV)%'
                port: '%env(DATABASE_PORT_SQLSRV)%'
                dbname: '%env(DATABASE_NAME_SQLSRV)%'
                password: '%env(DATABASE_PASSWORD_SQLSRV)%'
                user: '%env(DATABASE_USER_SQLSRV)%'
                driver: '%env(DATABASE_DRIVER_SQLSRV)%'
                charset: utf8

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: sqlsrv
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    SqlSrv : 
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/SqlSrv'
                        is_bundle: false
                        prefix: App\Entity\SqlSrv
                        alias: SqlSrv
